name: AQI MLOps Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # CACHE PIP (VERY IMPORTANT)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingestion
        env:
          API_KEY: ${{ secrets.API_KEY }}
          HOPSWORKS_KEY: ${{ secrets.HOPSWORKS_KEY }}
          LAT: 28.4212
          LON: 70.2989
        run: python -m ingestion.ingestion